// Generated by CoffeeScript 1.8.0
(function() {
  var Mpeg1Muxer, child_process, events, util;

  child_process = require('child_process');

  util = require('util');

  events = require('events');

  Mpeg1Muxer = function(options) {
    var self;
    self = this;
    this.url = options.url;
    this.transport = options.transport || "tcp";
    //console.log(options.width);
    var size ='';
    if (options.width != undefined && options.height != undefined){ 
        size = options.width + 'x' + options.height;
    }
    var ffmpegParams = [], lastParams = [];
    if(this.transport != "file")
        ffmpegParams = ["-rtsp_transport", this.transport];
    if(size == '') {
        lastParams = ["-i", this.url, '-f', 'mpeg1video', '-b:v', '800k', '-r', '30', '-'];
    }
    else {
        lastParams = ["-i", this.url, '-s', size ,'-f', 'mpeg1video', '-b:v', '800k', '-r', '30', '-'];
    }
    ffmpegParams = ffmpegParams.concat(lastParams);
    this.stream = child_process.spawn("ffmpeg", ffmpegParams, { detached: false });

    this.inputStreamStarted = true;
    this.stream.stdout.on('data', function(data) {
      return self.emit('mpeg1data', data);
    });
    this.stream.stderr.on('data', function(data) {
      return self.emit('ffmpegError', data);
    });
    return this;
  };

  util.inherits(Mpeg1Muxer, events.EventEmitter);

  module.exports = Mpeg1Muxer;

}).call(this);
